// @ts-nocheck
// Simple components that work without TypeScript issues

import React from "react"

// Export all simple components without TypeScript checking
export * from "./simple-accordion"
export * from "./simple-card"
export * from "./simple-badge"

// Re-export all other components with ts-nocheck
export * from "./accordion"
export * from "./alert"
export * from "./alert-dialog"
export * from "./avatar"
export * from "./badge"
export * from "./breadcrumb"
export * from "./button"
export * from "./calendar"
export * from "./card"
export * from "./carousel"
export * from "./chart"
export * from "./checkbox"
export * from "./collapsible"
export * from "./command"
export * from "./context-menu"
export * from "./dialog"
export * from "./drawer"
export * from "./dropdown-menu"
export * from "./form"
export * from "./hover-card"
export * from "./input"
export * from "./input-otp"
export * from "./label"
export * from "./menubar"
export * from "./navigation-menu"
export * from "./pagination"
export * from "./popover"
export * from "./progress"
export * from "./radio-group"
export * from "./resizable"
export * from "./scroll-area"
export * from "./select"
export * from "./separator"
export * from "./sheet"
export * from "./sidebar"
export * from "./skeleton"
export * from "./slider"
export * from "./sonner"
export * from "./switch"
export * from "./table"
export * from "./tabs"
export * from "./textarea"
export * from "./toast"
export * from "./toaster"
export * from "./toggle"
export * from "./toggle-group"
export * from "./tooltip"